feat: ttl based volatility offset and multiplier (ENG-803)
stryke-xyz/dopex-v2-clamm pull request #30
Opened 2024-05-09 00:49 UTC by psytama

2024-05-10 13:31 UTC, witherblock requested changes
Make a separate contract with V2_1 version

2024-05-20 21:40 UTC, Aercwarden commented on src/pricing/OptionPricingLinearV2_1.sol
> +        uint256 volatilityOffsetsLength = _volatilityOffsets.length;
```volatilityOffsetsLength```  doesn't need to be cached

2024-05-20 21:40 UTC, Aercwarden commented on src/pricing/OptionPricingLinearV2_1.sol
> +                uint256 balance = IERC20(xsyx).balanceOf(userAddress);
```balance``` can be moved out of the loop for gas efficiency

2024-05-21 17:00 UTC, witherblock approved these changes

2024-05-21 17:00 UTC, merged